# Generated by Django 4.1.3 on 2022-12-12 07:07

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=128, unique=True, verbose_name="用户名"),
                ),
                ("password", models.CharField(max_length=256, verbose_name="密码")),
                (
                    "email",
                    models.EmailField(max_length=254, unique=True, verbose_name="邮箱"),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="最后登录时间"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                (
                    "c_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="注册时间"),
                ),
                (
                    "has_confirmed",
                    models.BooleanField(default=False, verbose_name="确认时间"),
                ),
            ],
            options={
                "verbose_name": "身份",
                "verbose_name_plural": "身份",
                "ordering": ["-c_time"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, verbose_name="描述"),
                ),
                (
                    "introduction",
                    models.TextField(blank=True, max_length=1000, verbose_name="简介"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        upload_to=accounts.models.upload_to,
                        verbose_name="头像",
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        upload_to=accounts.models.upload_to,
                        verbose_name="封面",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.customuser",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={"verbose_name": "资料", "verbose_name_plural": "资料",},
        ),
        migrations.CreateModel(
            name="ConfirmString",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=256, verbose_name="确认码")),
                (
                    "c_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="确认时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.customuser",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "确认码",
                "verbose_name_plural": "确认码",
                "ordering": ["-c_time"],
            },
        ),
    ]
