# Generated by Django 4.1.3 on 2022-12-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("male", "男"), ("female", "女")],
                max_length=255,
                verbose_name="性别",
            ),
        ),
    ]
