# Generated by Django 4.1.3 on 2022-12-15 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_profile"),
    ]

    operations = [
        migrations.DeleteModel(name="Profile",),
    ]
